import { imgProjetos, imgTecnologias } from "./imagens.js";

const projetos = [
  {
    id: "0",
    nome: "Amazon Prime Fake",
    descricao: "",
    link: "https://felipegsg.github.io/projeto-back-end-final-2024/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.amazon,
    educacional: true,
  },
  {
    id: "1",
    nome: "EcoGoods",
    descricao: "",
    link: "https://felipegsg.github.io/Mercadinho-Nota-Fiscal/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.ecogoods,
    educacional: true,
  },
  {
    id: "2",
    nome: "Google Classroom Fake",
    descricao: "",
    link: "https://chat-fake-classroom.onrender.com/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.fakeClassroom,
    educacional: true,
  },
  {
    id: "3",
    nome: "Portifólio de jogos",
    descricao: "",
    link: "https://felipegsg.github.io/Portifolio-jogos/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.hallownest,
    educacional: true,
  },
  {
    id: "4",
    nome: "Sistema de ocorrências",
    descricao: "",
    link: "https://sistema-ocorrencias.onrender.com/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.ocorrencias,
    educacional: true,
  },
  {
    id: "5",
    nome: "Python - Flask",
    descricao: "",
    link: "https://python-e-flask.onrender.com/poo",
    linguagens: ["html", "python"],
    img: imgProjetos.edu.pythonFlask,
    educacional: true,
  },
  {
    id: "6",
    nome: "React - Vite",
    descricao: "",
    link: "https://primeiro-projeto-react-steel-phi.vercel.app/",
    linguagens: ["html", "react"],
    img: imgProjetos.edu.reactVite,
    educacional: true,
  },
  {
    id: "7",
    nome: "TechSolutions",
    descricao: "",
    link: "https://projeto-reactvite-blue.vercel.app/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.techsolutions,
    educacional: true,
  },
  {
    id: "8",
    nome: "To-do List",
    descricao: "",
    link: "https://felipegsg.github.io/to-do-list-localStorage/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.edu.todoList,
    educacional: true,
  },
  {
    id: "9",
    nome: "Clique-bolinha",
    descricao: "",
    link: "https://jogo-clique-bolinha.onrender.com/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.cliqueBolinha,
    educacional: false,
  },
  {
    id: "10",
    nome: "Cookie Clicker fake",
    descricao: "",
    link: "https://felipe-gabriel-souza-goncalves.github.io/fake-cookie-clicker/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.cookieClicker,
    educacional: false,
  },
  {
    id: "11",
    nome: "E-commerce jogos indies",
    descricao: "",
    link: "https://felipegsg.github.io/ecommerce-finalizado/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.ecommerce,
    educacional: false,
  },
  {
    id: "12",
    nome: "Jogo da velha",
    descricao: "",
    link: "https://felipe-gabriel-souza-goncalves.github.io/Jogo-da-velha/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.jogoDaVelha,
    educacional: false,
  },
  {
    id: "13",
    nome: "Gerenciador de matrizes",
    descricao: "",
    link: "https://felipe-gabriel-souza-goncalves.github.io/criador-matriz/matriz.html",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.matrizes,
    educacional: false,
  },
  {
    id: "14",
    nome: "Projeto relógio",
    descricao: "",
    link: "https://felipe-gabriel-souza-goncalves.github.io/Projeto-Relogio/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.relogio,
    educacional: false,
  },
  {
    id: "15",
    nome: "Manipulador de cores",
    descricao: "",
    link: "https://felipe-gabriel-souza-goncalves.github.io/RBG-Clip-Path-HTML/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.rgb,
    educacional: false,
  },
  {
    id: "16",
    nome: "Senhas aleatórias",
    descricao: "",
    link: "https://felipe-gabriel-souza-goncalves.github.io/Senhas_Aleatorias/",
    linguagens: ["html", "javascript"],
    img: imgProjetos.priv.senhasAleatorias,
    educacional: false,
  },
];

const tecnologias = {
  backEnd: [
    ["Javascript", "Python", "Java", "Node.js", "Dart", "PHP"],
    [
      imgTecnologias.back.javascript,
      imgTecnologias.back.python,
      imgTecnologias.back.java,
      imgTecnologias.back.node,
      imgTecnologias.back.dart,
      imgTecnologias.back.php,
    ],
  ],
  frontEnd: [
    ["HTML", "CSS", "React", "Flutter"],
    [
      imgTecnologias.front.html,
      imgTecnologias.front.css,
      imgTecnologias.front.react,
      imgTecnologias.front.flutter,
    ],
  ],
  outros: [
    ["Git", "Postman", "MySQL", "Figma", "Vscode"],
    [
      imgTecnologias.outros.git,
      imgTecnologias.outros.postman,
      imgTecnologias.outros.mysql,
      imgTecnologias.outros.figma,
      imgTecnologias.outros.vscode,
    ],
  ],
};

export { projetos, tecnologias };
